language: python

sudo: false

env:
    - CONDA="python=2.7"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - wget $URL -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels ioos --force
    - travis_retry conda create --yes -n TEST --file requirements.txt $CONDA
    - source activate TEST
    - travis_retry conda install --yes pytest

script:
    - py.test --verbose --ignore setup.py
